
SELECT * FROM APP.ALUNO ORDER BY NOME FETCH FIRST 100 ROWS ONLY;


SELECT * FROM APP.CURSO FETCH FIRST 100 ROWS ONLY;

SELECT * FROM APP.ALUNOCURSO FETCH FIRST 100 ROWS ONLY;

DELETE FROM APP.CURSO;
INSERT INTO APP.CURSO (ID, NOME, STATUSATIVO) VALUES (1, 'DIREITO', TRUE);
INSERT INTO APP.CURSO (ID, NOME, STATUSATIVO) VALUES (2, 'PEDAGOGIA', TRUE);
INSERT INTO APP.CURSO (ID, NOME, STATUSATIVO) VALUES (3, 'ENGENHARIA FLORESTAL', TRUE);
INSERT INTO APP.CURSO (ID, NOME, STATUSATIVO) VALUES (4, 'FILOSOFIA', TRUE);

DELETE FROM APP.ALUNO;
INSERT INTO APP.ALUNO (ID, CURSANDOTG, NOME, STATUSATIVO) VALUES (1, TRUE, 'DIEGO', TRUE);
INSERT INTO APP.ALUNO (ID, CURSANDOTG, NOME, STATUSATIVO) VALUES (2, TRUE, 'CARLA', TRUE);
INSERT INTO APP.ALUNO (ID, CURSANDOTG, NOME, STATUSATIVO) VALUES (3, TRUE, 'THIAGO', TRUE);
INSERT INTO APP.ALUNO (ID, CURSANDOTG, NOME, STATUSATIVO) VALUES (4, TRUE, 'JOAO PAULO', TRUE);
INSERT INTO APP.ALUNO (ID, CURSANDOTG, NOME, STATUSATIVO) VALUES (5, TRUE, 'ANDERSON', TRUE);

INSERT INTO APP.ALUNOCURSO (IDALUNO, IDCURSO) VALUES (1, 1);
INSERT INTO APP.ALUNOCURSO (IDALUNO, IDCURSO) VALUES (2, 1);
INSERT INTO APP.ALUNOCURSO (IDALUNO, IDCURSO) VALUES (3, 2);
INSERT INTO APP.ALUNOCURSO (IDALUNO, IDCURSO) VALUES (4, 3);
INSERT INTO APP.ALUNOCURSO (IDALUNO, IDCURSO) VALUES (5, 3);

